banner /EFI/refind/themes/cosmic-dark/background.png
banner_scale fillscreen
selection_big /EFI/refind/themes/cosmic-dark/selection_big.png
selection_small /EFI/refind/themes/cosmic-dark/selection_small.png
icons_dir /EFI/refind/themes/cosmic-dark/icons
